# Site settings
title: Duochrome | A minimal, Monochrome theme with a splash of color
description: "A minimal, Monochrome Jekyll theme with a splash of color."
url: "http://deadPix3l.github.io/duochrome"
authors:
  duochrome:
    name: "Skyler Curtis"
    email: "skylerr.curtis@gmail.com"
    url: "https://deadPix3l.github.com"

  monochrome:
    name: "The Review Index"
    email: "dyutibarma@gmail.com"
    url: "https://thereviewindex.com"

# Build settings
baseurl: /duochrome # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
reverse: false

#color options:
header-color: true
title-color: false
listing-color: false
header-flair: true
